apiVersion: v1
kind: Service
metadata:
  name: simple-web-monitoring-service
spec:
  type: LoadBalancer
  selector:
    app: simple-web-monitoring-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
